### ISSUE TITLE
Panic when trying to restart Graphics thread

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#1043]
I am running my graphics thread as a child of my logic thread. When I change the configuration, I kill the logic thread and restart it. This is causing a problem with the graphics thread. When it tries to restart it throws this panic:

```
thread 'graphics' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
stack backtrace:
   0: 0x55180637 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcab99e0793da62c7
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: 0x5517ce97 - std::sys_common::backtrace::_print::hbfe5b0c7e79c0711
                       at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: 0x55185d87 - std::panicking::default_hook::{{closure}}::h9ba2c6973907a2be
                       at /checkout/src/libstd/sys_common/backtrace.rs:60
                       at /checkout/src/libstd/panicking.rs:355
   3: 0x551857e7 - std::panicking::default_hook::he4d55e2dd21c3cca
                       at /checkout/src/libstd/panicking.rs:371
   4: 0x5518624f - std::panicking::rust_panic_with_hook::ha138c05cd33ad44d
                       at /checkout/src/libstd/panicking.rs:549
   5: 0x55186103 - std::panicking::begin_panic::hcdbfa35c94142fa2
                       at /checkout/src/libstd/panicking.rs:511
   6: 0x55186043 - std::panicking::begin_panic_fmt::hc09fe500d9b7be81
                       at /checkout/src/libstd/panicking.rs:495
   7: 0x55185fdf - rust_begin_unwind
                       at /checkout/src/libstd/panicking.rs:471
   8: 0x551aaca3 - core::panicking::panic_fmt::h883a028e9f4b4457
                       at /checkout/src/libcore/panicking.rs:69
   9: 0x551aabef - core::panicking::panic::hdb3cf3207dda37bb
                       at /checkout/src/libcore/panicking.rs:49
  10: 0x54c8f927 - winit::platform::platform::EventsLoop::poll_events::h879f31f03afb0c6c
  11: 0x54dd76a7 - foobar::graphics::main_loop::<impl foobar::graphics::Graphics>::start::{{closure}}::h6379807ce069cbb5
  12: 0x54c1b803 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9262917407ae443
  13: 0x54c1ca4f - std::panicking::try::do_call::h6288a917caa829f7
  14: 0x5518b3ff - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:98
  15: 0x54c77c4b - <F as alloc::boxed::FnBox<A>>::call_box::h8587d7fddd8096d7
  16: 0x55184d37 - std::sys::imp::thread::Thread::new::thread_start::h227b2afaa9316a8d
                       at /checkout/src/liballoc/boxed.rs:658
                       at /checkout/src/libstd/sys_common/thread.rs:21
                       at /checkout/src/libstd/sys/unix/thread.rs:84
2017-08-08T23:28:04.429813553+00:00 - Graphics Thread Died: "SendError(..)"
```

The code which I believe is causing the issue:
```
events_loop.poll_events(|event| {

    match event.clone() {
        glium::glutin::Event::WindowEvent { event, .. } => match event {
            glium::glutin::WindowEvent::Closed |
            glium::glutin::WindowEvent::KeyboardInput {
                input: glium::glutin::KeyboardInput {
                    virtual_keycode: Some(glium::glutin::VirtualKeyCode::Escape),
                    ..
                },
                ..
            } => return (),
            _ => (),
        },
        _ => (),
    }

    // Use the `winit` backend feature to convert the winit event to a conrod one.
    if let Some(event) = conrod::backend::winit::convert_event(event, &display) {
        ui.handle_event(event);
    } else {
        return ();
    }
});
```

There is no unwrap there so I am a little confused as to what exactly is causing the error.

**Comment by tl8roy** [comment]
If I comment that section out, then the error doesn't occur. The problem then is that the touchscreen can't work.
