### ISSUE TITLE
examples/canvas doesn't compile

### ISSUE THREAD

**Issue by smcmurray** [PistonDevelopers/conrod#1093]
$ rustc --version
rustc 1.21.0

$ cargo --version
cargo 0.22.0

$ head -3 Cargo.toml 
[package]
name = "conrod"
version = "0.56.0"

$ uname -or
4.13.9-300.fc27.x86_64 GNU/Linux

$ cargo run --release --features "winit glium" --example canvas
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', src/libcore/option.rs:819:4

**Comment by mitchmindtree** [comment]
Thanks for the issue!

> thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', src/libcore/option.rs:819:4

This line seems to indicate that you may not have the "libwayland-egl" installed - do you have this installed? It looks like there are some related results when searching the error.

**Comment by shanehandley** [comment]
Closing due to inactivity.
