### ISSUE TITLE
Examples all_winit_gfx 'NoAvailablePixelFormat'

### ISSUE THREAD

**Issue by norru** [PistonDevelopers/conrod#1094]
On Linux Devuan Ceres

```
nico@lenovo-devuan:~/Projects/3rdParty/conrod$ RUST_BACKTRACE=1 cargo run --no-default-features --features="winit gfx_rs" --example all_winit_gfx
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/all_winit_gfx`
error: XDG_RUNTIME_DIR not set in the environment.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: gfx_window_glutin::init_raw
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.18.0/src/lib.rs:126
  12: gfx_window_glutin::init
             at /home/nico/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.18.0/src/lib.rs:58
  13: all_winit_gfx::feature::main
             at examples/all_winit_gfx.rs:60
  14: all_winit_gfx::main
             at examples/all_winit_gfx.rs:19
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  16: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:59
  17: main
  18: __libc_start_main
  19: _start
```
If it helps, many Linux distributions are now affected by this: https://bugs.freedesktop.org/show_bug.cgi?id=102354

**Comment by OtaK** [comment]
Remove the multisampling and it will work fine.

**Comment by norru** [comment]
Nope, removed multisampling, error is still there. Error goes away if I switch from Srgba8 to Rgba8 or run on NVidia. It is a known issue in Mesa 17.2.

**Comment by daboross** [comment]
Ubuntu 16.04 w/ Lenovo Carbon X1 5th Gen also affected. I don't use gfx backend, but just noting this.
