### ISSUE TITLE
Systems without SRGB support unable to use gfx backend

### ISSUE THREAD

**Issue by daboross** [PistonDevelopers/conrod#1128]
Hi,

This isn't an urgent issue for me, as I am not using the gfx backend, but here it is anyways.

When trying out the examples to ensure updated dependencies worked, I ran into an issue with the 'gfx' one. Specifically:

```
$ RUST_BACKTRACE=1 cargo run --all-features --example all_winit_gfx
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/all_winit_gfx`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', libcore/result.rs:945:5
``` 
<details><summary>(backtrace)</summary>

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: gfx_window_glutin::init_raw
             at /home/daboross/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.20.0/src/lib.rs:145
  12: gfx_window_glutin::init
             at /home/daboross/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.20.0/src/lib.rs:67
  13: all_winit_gfx::feature::main
             at examples/all_winit_gfx.rs:60
  14: all_winit_gfx::main
             at examples/all_winit_gfx.rs:19
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```

</details>

I believe this issue stems from my system lacking something to do with srgb, as changing `conrod::backend::gfx::ColorFormat` from `Srgba8` to `Rgba8` lets the example work correctly. Probably the same root cause on my system as the [srgb issue with piston-window](https://github.com/PistonDevelopers/piston_window/issues/139).

If someone wants to pursue this, I can do any testing and provide further information, but it's not a priority for me. I'm using the glium backend for everything I've made, and it does work well.

My graphics controller is:

```
$ sudo lspci -k
...
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
	Subsystem: Lenovo HD Graphics 620 (ThinkPad X1 Carbon 5th Gen)
	Kernel driver in use: i915
	Kernel modules: i915
...
```

**Comment by daboross** [comment]
Nevermind, duplicate of https://github.com/PistonDevelopers/conrod/issues/1094.
