### ISSUE TITLE
Unwrapped Err: SamplersNotSupported

### ISSUE THREAD

**Issue by TheDan64** [PistonDevelopers/conrod#1148]
I'm on Ubuntu 16 LTS trying to run an example:
`cargo run --release --features="winit glium" --example canvas`

but I get the following error:
```text
OpenGL Warning: glXChooseVisual: ignoring attribute 0x22
OpenGL Warning: glXChooseVisual: bad attrib=0x186a0, ignoring
OpenGL Warning: glXChooseVisual: bad attrib=0x186a1, ignoring
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SamplersNotSupported', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: conrod::backend::glium::Renderer::draw
  11: canvas::feature::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  15: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by mitchmindtree** [comment]
Thanks for the issue!

Hmm it looks like maybe the texture sampler we're using in the glium backend is not supported by your platform? Does the [glium image example](https://github.com/glium/glium/blob/master/examples/image.rs) work on your machine? If not there may be some OpenGL lib you need to install, or maybe your particular graphics hardware simply does not support texture sampling? What hardware are you using (graphics card in particular)?
