### ISSUE TITLE
Examples not running

### ISSUE THREAD

**Issue by Talw3g** [PistonDevelopers/conrod#1169]
I've just cloned the repo and tried to run the examples as described in the documentation ([here](http://docs.piston.rs/conrod/conrod/guide/chapter_2/index.html#running-the-conrod-examples)), but got a runtime error:

```bash
cargo run --release --features "winit glium" --example primitives
Finished release [optimized] target(s) in 0.16 secs
Running `target/release/examples/primitives`
thread 'main' panicked at 'No backend is available', /home/thibault/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/platform/linux/mod.rs:356:9`
```

Here is the backtrace:
```bash
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
   6: winit::EventsLoop::new
   7: primitives::feature::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  11: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  12: main
  13: __libc_start_main
  14: _start
```
The same issue occurs for the 4 examples listed in the doc.
It seems to come from a known issue from winit ([#392](https://github.com/tomaka/winit/issues/392)), which should have been resolved in winit-13.1... But I tried, and conrod doesn't seem to be compatible with this version of winit.
Please let me know if I can provide any info to help.

**Comment by shanehandley** [comment]
Closing due to inactivity (and unable to reproduce)
