### ISSUE TITLE
example fails to build on Windows 7 64-bit with Rust 1.25

### ISSUE THREAD

**Issue by mark-summerfield** [PistonDevelopers/conrod#1172]
Here's the output with most downloads & compiles elided, following the instructions given in chapter 2 of the manual:
```
R:\rs\conrod>cargo run --release --features "winit glium" --example all_winit_glium
 Downloading piston_window v0.75.0
...
   Compiling piston_window v0.75.0
   Compiling conrod v0.59.1 (file:///R:/rs/conrod)
    Finished release [optimized] target(s) in 137.11 secs
     Running `target\release\examples\all_winit_glium.exe`
OpenGL Warning: WGL_SAMPLE_BUFFERS_EXT & WGL_SAMPLES_EXT not supporteed!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: lutinCreationError(NoAvailablePixelFormat)', libcore\result.rs:945:5 note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\examples\all_winit_glium.exe` (exit code: 101)
```
I also tried using gfx:
```
R:\rs\conrod>cargo run --release --no-default-features --features="winit gfx_rs" --example all_winit_gfx
   Compiling conrod v0.59.1 (file:///R:/rs/conrod)
warning: type alias is never used: `DepthFormat`
   --> src\backend\gfx.rs:107:1
... many more warnings elided ...
    Finished release [optimized] target(s) in 24.95 secs
     Running `target\release\examples\all_winit_gfx.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', libcore\result.rs:945:5 note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\examples\all_winit_gfx.exe` (exit code: 101)
```
And finally I tried:
```
R:\rs\conrod>cargo run --release --no-default-features --features="piston" --example all_winit_piston
error: no example target named `all_winit_piston`

R:\rs\conrod>cargo run --release --no-default-features --features="piston" --example all_piston_window
   Compiling conrod v0.59.1 (file:///R:/rs/conrod)
warning: unnecessary parentheses around function argument
   --> src\backend\piston\draw.rs:265:36
... couple of warnings elided ...
    Finished release [optimized] target(s) in 25.12 secs
     Running `target\release\examples\all_piston_window.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t find any pixel format that matches the criterias."', libcore\result.rs:945:5 note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\release\examples\all_piston_window.exe` (exit code: 101)
```
This last one does actually create a window---but it disappears immediately as the program crashes.
I also think it would help if the manual showed these two other options, especially if they were to work:-)

**Comment by shanehandley** [comment]
Closing: Old release.
