### ISSUE TITLE
Issues while running examples on NixOS ("both libglx and libEGL not present")

### ISSUE THREAD

**Issue by Gonzih** [PistonDevelopers/conrod#1302]
Hi there, 

Sorry for being another NixOS user who is unable to run examples on their system, I found all nixos related issues in conrod, piston and glutin repos but nothing helped me to solve my problem.

I'm simply trying to run examples. I use nix shell to make sure i have all needed libraries.

### What command I run in this repo?

```
nix-shell shell.nix --run 'cargo run --release --features "winit glium" --example all_winit_glium'
```

### What is my nix-shell configuration?
```nix
let
   pkgs = import <nixpkgs> {};
in pkgs.stdenv.mkDerivation rec {
  buildInputs = with pkgs; [
    stdenv
    rustup
    cargo
    cairo
    glib
    xwayland
    freetype
    weston
    wayland
    glfw
    SDL2
    x11
    libcaca
    xorg.libX11
    cmake
    gnumake
    xorg.libXrandr
    xorg.libxcb
  ];
  LD_LIBRARY_PATH = with pkgs.xlibs; "${pkgs.mesa}/lib:${libX11}/lib:${libXcursor}/lib:${libXxf86vm}/lib:${libXi}/lib:${libXtst}/lib:${libXrandr}/lib:${libxcb}/lib";
}
```

### What error am I getting?
```
nix-shell shell.nix --run 'cargo run --release --features "winit glium" --example all_winit_glium'
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/examples/all_winit_glium`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NotSupported("both libglx and libEGL not present"))', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### RUST_BACKTRACE=1 output
<details>

```
nix-shell shell.nix --run 'env RUST_BACKTRACE=1 cargo run --release --features "winit glium" --example all_winit_glium'
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/examples/all_winit_glium`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NotSupported("both libglx and libEGL not present"))', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: all_winit_glium::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: std::panicking::try
             at src/libstd/panicking.rs:271
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

At this point I'm out of ideas so any help/questions/information would be very helpful, thank you for your time reading through this!

**Comment by jordanbray** [comment]
This is due to the weird way nixos handles dependencies.  I recommend using the following setup.

Install direnv (or don't), and hook it into your shell with `eval "$(direnv hook bash)"`.

project_root/.envrc
```
use_nix
```

project_root/shell.nix
```
moz_overlay = import (builtins.fetchTarball https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz);
  nixpkgs = import <nixpkgs> { overlays = [ moz_overlay ]; };
  #rustNightlyChannel = (nixpkgs.rustChannelOf { date = "2019-01-26"; channel = "nightly"; }).rust;
  rustStableChannel = nixpkgs.latest.rustChannels.stable.rust.override {
    extensions = [
      "rust-src"
      "rls-preview"
      "clippy-preview"
      "rustfmt-preview"
    ];
  };
in
with import <nixpkgs> {}; {
  lyzsEnv = stdenv.mkDerivation {
    name = "YOURPROJECTNAME";
    buildInputs = [ rustStableChannel rls pkgconfig python3 xorg.libxcb xorg.libX11 wayland wayland-protocols patchelf libGLU_combined ];
  };
}
```

Now, whenever you change into the project directory, `shell.nix` will be activated.

This is where the magic happens - in run.sh.  This replaces the "missing" dependencies in your executable with the correct versions in nixos, due tho them being installed in a weird place.

project_root/run.sh
```
WAYLAND="$(nix eval nixpkgs.wayland.outPath | sed 's/"//g')/lib"
LIBXCB="$(nix eval nixpkgs.xorg.libxcb.outPath | sed 's/"//g')/lib"
LIBGLU="$(nix eval nixpkgs.libGLU_combined.outPath | sed 's/"//g')/lib"

echo $WAYLAND $LIBXCB $LIBGLU

cargo build --release &&
find ./target/ -type f -name YOURPACKAGENAME -exec patchelf --set-rpath "$WAYLAND:$LIBXCB:$LIBGLU" '{}' \; &&
cargo run --release
```

**Comment by Gonzih** [comment]
Ok, thanks for the info, will give it a try! Closing issue for now.
