### ISSUE TITLE
Examples panic in LinkedHashMap<K,V,S>::insert

### ISSUE THREAD

**Issue by alopatindev** [PistonDevelopers/conrod#1399]
```
$ RUST_BACKTRACE=full cargo run --example file_navigator
warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
    --> backends/conrod_glium/./src/lib.rs:1022:54
     |
1022 |             RendererCreationError::Texture(ref e) => std::error::Error::description(e),
     |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
    --> backends/conrod_glium/./src/lib.rs:1023:54
     |
1023 |             RendererCreationError::Program(ref e) => std::error::Error::description(e),
     |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
    --> backends/conrod_glium/./src/lib.rs:1052:41
     |
1052 |             DrawError::Buffer(ref e) => std::error::Error::description(e),
     |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
    --> backends/conrod_glium/./src/lib.rs:1053:39
     |
1053 |             DrawError::Draw(ref e) => std::error::Error::description(e),
     |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: 4 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/file_navigator`
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<u32, conrod_core::text::rt::gpu_cache::Row>` uninitialized, which is invalid', /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:     0x55cf89b83840 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55cf89b83840 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55cf89b83840 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55cf89b83840 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55cf89ba531c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55cf89b7fb42 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55cf89b85c2d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55cf89b85c2d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55cf89b85c2d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55cf89b858d8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55cf89b86311 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55cf89b85eb9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55cf89b83cac - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55cf89b85e79 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55cf89ba31f1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55cf89ba313d - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x55cf892f3e50 - core::mem::uninitialized::h5cbffd4e2e5148be
                               at /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
  17:     0x55cf892f3e50 - linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node::h26e2edb379cfd177
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174
  18:     0x55cf892f4132 - linked_hash_map::LinkedHashMap<K,V,S>::insert::hc74b2aa20671cb3c
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304
  19:     0x55cf89387991 - rusttype::gpu_cache::Cache::cache_queued::h164f9afb6beacd98
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.8.2/src/gpu_cache.rs:783
  20:     0x55cf89422565 - conrod_glium::Renderer::fill::h8ec7adea508e3e79
                               at /home/al/git-extra/conrod/backends/conrod_glium/./src/lib.rs:710
  21:     0x55cf89436941 - file_navigator::main::{{closure}}::h5cd5e77f6f4324c6
                               at /home/al/git-extra/conrod/backends/conrod_glium/examples/file_navigator.rs:110
  22:     0x55cf892fcd46 - file_navigator::support::run_loop::{{closure}}::h20a6571fa8ad9e00
                               at /home/al/git-extra/conrod/backends/conrod_glium/examples/support/mod.rs:88
  23:     0x55cf892fc105 - winit::platform_impl::platform::sticky_exit_callback::h56a8b6c1af919bb6
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:726
  24:     0x55cf89389cf2 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h2a68170182a5dff3
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:308
  25:     0x55cf8938ac4b - winit::platform_impl::platform::x11::EventLoop<T>::run::hf731dd5c5e56deb4
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:386
  26:     0x55cf892fbde1 - winit::platform_impl::platform::EventLoop<T>::run::hfbf53df1f53b2b87
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:642
  27:     0x55cf8940c0c3 - winit::event_loop::EventLoop<T>::run::h6861b1cd57c7cafe
                               at /home/al/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154
  28:     0x55cf892fc78d - file_navigator::support::run_loop::ha9551615b97bd467
                               at /home/al/git-extra/conrod/backends/conrod_glium/examples/support/mod.rs:33
  29:     0x55cf89466b5d - file_navigator::main::hc2a9c90c654c485b
                               at /home/al/git-extra/conrod/backends/conrod_glium/examples/file_navigator.rs:52
  30:     0x55cf893b2beb - core::ops::function::FnOnce::call_once::h6b5a562c29c031e4
                               at /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  31:     0x55cf892f379e - std::sys_common::backtrace::__rust_begin_short_backtrace::hc3b27b4764e07a43
                               at /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  32:     0x55cf893d6ac1 - std::rt::lang_start::{{closure}}::hc81a08bf32247ca5
                               at /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  33:     0x55cf89b86827 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  34:     0x55cf89b86827 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  35:     0x55cf89b86827 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  36:     0x55cf89b86827 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  37:     0x55cf89b86827 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  38:     0x55cf893d6a97 - std::rt::lang_start::h781128409c953239
                               at /home/al/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  39:     0x55cf89466d8a - main
  40:     0x7f12ebafdd0b - __libc_start_main
  41:     0x55cf892ef1ba - _start
  42:                0x0 - <unknown>
$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
$ uname -mo
x86_64 GNU/Linux
```

**Comment by alopatindev** [comment]
This issue is fixed in linked-hash-map 0.5.3. As rusttype depends on linked-hash-map 0.5 — I guess this issue can be closed. It'd be better if rusttype depended on linked-hash-map ^0.5.3 though.
