### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#485]
Might require opengl_graphics to update dependencies as well.

**Comment by bvssvni** [comment]
I'm getting some weird errors when updating the dependencies:

```
thread '<unnamed>' panicked at 'no entry found for key', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:731
```

**Comment by bvssvni** [comment]
It seems Cargo hangs.

**Comment by bvssvni** [comment]
Running with `RUST_BACKTRACE=1 cargo test`:

```
thread '<unnamed>' panicked at 'no entry found for key', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
stack backtrace:
   1:        0x10a39a8e5 - sys::backtrace::write::h6e963597537e900csas
   2:        0x10a3a17f4 - panicking::on_panic::hc6a54e36471e710eOtw
   3:        0x10a37bbd8 - rt::unwind::begin_unwind_inner::hc2503abaf1a353b16bw
   4:        0x10a37c36c - rt::unwind::begin_unwind_fmt::h5191fd3526b65934cbw
   5:        0x10a3a10ac - rust_begin_unwind
   6:        0x10a3c5225 - panicking::panic_fmt::h77445f1832864594i5B
   7:        0x10a133cc2 - ops::cargo_rustc::rustc::closure.33096
   8:        0x10a133336 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h2785876919849651134
   9:        0x10a0f3569 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h1688256377523264599
  10:        0x10a202532 - ops::cargo_rustc::job::F.FnBox<A, R>::call_box::h14669685106895006122
  11:        0x10a11ebed - F.FnBox::call_box::h13519971316597680418
  12:        0x10a261ecb - boxed::F.FnBox<A>::call_box::h5956848479252763573
  13:        0x10a260b17 - rt::unwind::try::try_fn::h4043412221538007623
  14:        0x10a3a3698 - rust_try_inner
  15:        0x10a3a3685 - rust_try
  16:        0x10a392ef5 - rt::unwind::try::inner_try::hf8418fa68612ccb4Z7v
  17:        0x10a260d72 - boxed::F.FnBox<A>::call_box::h10946525392169938074
  18:        0x10a3a017d - sys::thread::Thread::new::thread_start::h143ebbdca41cb5fdywv
  19:     0x7fff95cf4898 - _pthread_body
  20:     0x7fff95cf4729 - _pthread_start
```

**Comment by bvssvni** [comment]
Somebody told me `cargo test -j 1` works, and it worked!

**Comment by Kagami** [comment]
Weird, seems like race in cargo?
