### ISSUE TITLE
all_widgets example panic

### ISSUE THREAD

**Issue by kyrias** [PistonDevelopers/conrod#899]
I'm not sure if this is a rustc bug or a conrod one, but I'm getting the following with rustc 1.15.0-nightly (71c06a56a 2016-12-18):

```
thread 'main' panicked at 'attempt to subtract with overflow', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:336
stack backtrace:
   1:     0x558111baeeea - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x558111bb258f - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x558111bb218e - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x558111bb2a37 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x558111bb28c4 - std::panicking::begin_panic::hbd10b7f500042f98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x558111bb27e9 - std::panicking::begin_panic_fmt::h49583ddd44614a0d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x558111bb2777 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x558111bde60d - core::panicking::panic_fmt::h3b787d0ceafd7204
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x558111bde544 - core::panicking::panic::h57808c0fa90ee3ee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55811164c9ef - <u32 as core::ops::Sub>::sub::h065d64ae304f864c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:336
  11:     0x558111658435 - <rusttype::geometry::Rect<N>>::width::h6c1bda04fa372a3d
                        at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.2.1/src/geometry.rs:156
  12:     0x55811169d060 - conrod::backend::piston::gfx::cache_queued_glyphs::h21e89649b6e00ab5
                        at /home/kyrias/code/conrod/src/backend/piston/gfx.rs:271
  13:     0x55811154f477 - conrod::backend::piston::gfx::draw::{{closure}}::h303633ea747fb276
                        at /home/kyrias/code/conrod/src/backend/piston/gfx.rs:190
  14:     0x5581114a4ab7 - core::ops::impls::<impl core::ops::FnMut<A> for &'a mut F>::call_mut::h77891287c094d581
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:2635
  15:     0x55811155a8de - conrod::backend::piston::draw::primitive::{{closure}}::habbf99796c1b8982
                        at /home/kyrias/code/conrod/src/backend/piston/draw.rs:151
  16:     0x5581115ea551 - rusttype::gpu_cache::Cache::cache_queued::hd2db7fb8f35d8bb5
                        at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.2.1/src/gpu_cache.rs:431
  17:     0x558111556dde - conrod::backend::piston::draw::primitive::h57b9f73265d81591
                        at /home/kyrias/code/conrod/src/backend/piston/draw.rs:150
  18:     0x55811154f78f - conrod::backend::piston::draw::primitives::h8b60cd531c2f16b2
                        at /home/kyrias/code/conrod/src/backend/piston/draw.rs:48
  19:     0x55811154f385 - conrod::backend::piston::gfx::draw::h85a399b95a188af0
                        at /home/kyrias/code/conrod/src/backend/piston/gfx.rs:193
  20:     0x5581115f8b96 - all_widgets::main::{{closure}}::hb983c263062ecfa5
                        at /home/kyrias/code/conrod/examples/all_widgets.rs:69
  21:     0x5581114995a0 - <gfx_graphics::back_end::Gfx2d<R>>::draw::hcc2f07eeb8e45bb0
                        at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/piston2d-gfx_graphics-0.33.2/src/back_end.rs:314
  22:     0x55811154f0df - conrod::backend::piston::gfx::GfxContext::draw_2d::h5512eef7bbfa036a
                        at /home/kyrias/code/conrod/src/backend/piston/gfx.rs:104
  23:     0x5581114cf699 - <conrod::backend::piston::window::Window<W>>::draw_2d::h313750c6bc0c2415
                        at /home/kyrias/code/conrod/src/backend/piston/window.rs:137
  24:     0x5581115f85ce - all_widgets::main::h0649ab859a7fd1ee
                        at /home/kyrias/code/conrod/examples/all_widgets.rs:66
  25:     0x558111bb98fa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  26:     0x558111bb3176 - std::rt::lang_start::ha749a62502c90792
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  27:     0x5581115f9c92 - main
  28:     0x7f2d6bb4b290 - __libc_start_main
  29:     0x5581113d71c9 - _start
  30:                0x0 - <unknown>
zsh: exit 101   RUST_BACKTRACE=1 cargo run --example all_widgets
```

**Comment by andrewcsmith** [comment]
I had the same issue. On my computer, it works with nightly 2016-12-16 but breaks in later nightlies. It should break whenever you attempt to draw any text at all.

**Comment by mitchmindtree** [comment]
Huh, strange! Judging by this part of the stacktrace

```
   9:     0x558111bde544 - core::panicking::panic::h57808c0fa90ee3ee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55811164c9ef - <u32 as core::ops::Sub>::sub::h065d64ae304f864c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:336
  11:     0x558111658435 - <rusttype::geometry::Rect<N>>::width::h6c1bda04fa372a3d
                        at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.2.1/src/geometry.rs:156
  12:     0x55811169d060 - conrod::backend::piston::gfx::cache_queued_glyphs::h21e89649b6e00ab5
                        at /home/kyrias/code/conrod/src/backend/piston/gfx.rs:271
```

it seems to have something to do with the calculation of the width of the rusttype Rect [here](https://github.com/PistonDevelopers/conrod/blob/master/src/backend/piston/gfx.rs#L271), which is produced by the `rusttype::gpu_cache::GpuCache::cache_glyphs` method. It seems like the `Rect`'s `min.x` is somehow greater than the `max.x`, causing the `u32` underflow?

Do either of you get this error when running either of the [rusttype examples](https://github.com/dylanede/rusttype/tree/master/examples)? If so, it might be best for us to move this to the rusttype repo. Also, do you get this same error for the `glutin_glium.rs` example? *Also*, does it occur when built with both debug and release? Or only when built with debug?

**Comment by andrewcsmith** [comment]
`glutin_glium.rs`: works
`glutin_gfx.rs`: works
`rusttype examples`: works
`all_widgets.rs`: release and debug both crash

It seems to occur any time the screen draws a text widget. I have another app where I just drew a TextBox and as soon as I typed a letter, the program crashed.

Late 2011 MBP running 10.10 btw.
