### ISSUE TITLE
Conrod example doesn't work

### ISSUE THREAD

**Issue by CackboneML** [PistonDevelopers/conrod#900]
Hello, i have problem when i'm try conrod examples: 

```
RUST_BACKTRACE=1 cargo run --release --example canvas
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/canvas`
thread 'main' panicked at 'Failed to get root window: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 154, minor_code: 5 }', ../src/libcore/result.rs:837
stack backtrace:
   1:     0x55d54256646a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55d54256abef - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x55d542568f06 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x55d5425695b7 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55d542569444 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x55d542569369 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x55d5425692f7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x55d5425a0f5d - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x55d542501038 - core::result::unwrap_failed::heeb92ebcc3f815a8
  10:     0x55d5425154a0 - glutin::platform::platform::x11::Window::new::heaf72961880df739
  11:     0x55d542515c7c - glutin::window::<impl glutin::WindowBuilder<'a>>::build::h473cba0f596871ba
  12:     0x55d5424e8e53 - glutin_window::GlutinWindow::new::h0c70d721fdf4399a
  13:     0x55d5424ea588 - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::hc33a2dfe7794d743
  14:     0x55d54247013c - canvas::main::heb537b77f0925e0e
  15:     0x55d5425726ca - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  16:     0x55d542569fd5 - std::rt::lang_start::hd661476ce2fc2931
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  17:     0x7fae22909290 - __libc_start_main
  18:     0x55d5424296a9 - _start
  19:                0x0 - <unknown>
```

**Comment by mitchmindtree** [comment]
Hi, thanks for the issue! The example has since been updated, does it work for you now?

If not, could you please let me know if the examples at [tomaka/glutin](https://github.com/tomaka/glutin) and [tomaka/glium](https://github.com/tomaka/glium) also do not work for you?

**Comment by mitchmindtree** [comment]
I'm going to close this for now, but feel free to re-open if the example still does not work for you.
