### ISSUE TITLE
Glutin GFX Example

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#907]
I was trying different backends to get one to work on a Raspberry Pi. With a bit of coercing, I managed to get the GFX example to partially work.

The issue I am having is two-fold:
Firstly using the 1.40 shader, it renders the text fine, but none of the other widgets or colours.
![gfx_issue](https://cloud.githubusercontent.com/assets/3813500/22188382/4c033aec-e160-11e6-8c5e-7677e1cb1df9.png)

Secondly, the Pi Graphics Driver only supports OpenGL 2.1. This means that the supported shader is version 1.20. I made an attempt to backport the shader to 1.20, but while it runs, not even the text shows.

I would like to get it to work on OpenGL 2.1 as this would probably partially solve the issue in #890

**Comment by tl8roy** [comment]
Just tried the 1.40 version using the software render on the Pi. The text does display but has white blocks around it,

**Comment by mitchmindtree** [comment]
The GFX example is incomplete (I think the only `render::Primitive` being drawn at the moment is `Text`?) and requires some refactoring. I think the glium example should provide a clear demo of how to complete the GFX one though, as the GFX one is also using opengl.

Did you have any luck with the `glutin_glium.rs` example? Perhaps it would work if we added another [shader pair](https://github.com/PistonDevelopers/conrod/blob/master/src/backend/glium.rs#L117-L163) to the backend for version 120 and add them to the list of associated version + shader pairs [here](https://github.com/PistonDevelopers/conrod/blob/master/src/backend/glium.rs#L234-L235)? It might be easier to get that working than the GFX example?

**Comment by tl8roy** [comment]
Ok, I thought it might be incomplete, but wasn't sure. Yes, ```Text``` is all that shows up.

The ```glutin_glium.rs``` will boot on the software render, but just has a white screen. I am not sure what is happening with that.

I think adding another pair for 120 is a good idea. I made a bit of a start but got:
```Program(ProgramCreationError(CompilationError("0:7(2): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end\n")))',``` when it tried to build the shader.
This wasn't very helpful in letting me know what was wrong.
```
/// The vertex shader used within the `glium::Program` for OpenGL.
pub const VERTEX_SHADER_GL: &'static str = "
    #version 120

    vec2 position;
    vec2 tex_coords;
    vec4 color;
    uint mode;

    vec2 v_tex_coords;
    vec4 v_color;
    uint v_mode;

    void main() {
        gl_Position = vec4(position, 0.0, 1.0);
        v_tex_coords = tex_coords;
        v_color = color;
        v_mode = mode;
    }
";

/// The fragment shader used within the `glium::Program` for OpenGL.
pub const FRAGMENT_SHADER_GL: &'static str = "
    #version 120
    uniform sampler2D tex;

    vec2 v_tex_coords;
    vec4 v_color;
    uint v_mode;

    vec4 f_color;

    void main() {
        // Text
        if (v_mode == uint(0)) {
            f_color = v_color * vec4(1.0, 1.0, 1.0, texture2D(tex, v_tex_coords).r);

        // Image
        } else if (v_mode == uint(1)) {
            f_color = texture2D(tex, v_tex_coords);

        // 2D Geometry
        } else if (v_mode == uint(2)) {
            f_color = v_color;
        }
    }
";
```

**Comment by mitchmindtree** [comment]
Hey @tl8roy, I've been having a go at getting a pair of GLSL 120 shaders working tonight. It appears there's quite a big jump between 120 and 140!

I've had a go at writing a GLSL 120 shader pair [here](https://github.com/mitchmindtree/conrod/blob/glium_glsl_120/src/backend/glium.rs#L117-L161) on my `glium_glsl_120` branch. On my machine the shader seems to parse OK, however the program is rejected due to a `SamplersNotSupported` error, suggesting that the `GL_ARB_sampler_objects` extension is not supported on my hardware. However, apparently most hardware supports the `GL_ARB_sampler_objects` extension so it may be that my machine is a unique case. Do you think you could clone and test the `glutin_glium.rs` example on my [`glium_glsl_120` branch](https://github.com/mitchmindtree/conrod/tree/glium_glsl_120) on your raspberry pi and let me know the output?

Btw, the `SamplersNotSupported` error refers to the `uniform sampler2d tex;` declaration in the fragment shader. This sampler allows us to sample either the texture that we use to cache text onto the GPU when drawing text, or the textures associated with images depending on the `mode`, so it would be great to get this working. I'm not yet sure what other ways there are to efficiently sample from a texture in glsl 120 but I'll look into it in the meantime.

**Comment by tl8roy** [comment]
@mitchmindtree I won't be able to test on Hardware until Friday, but I did find this: https://github.com/anholt/mesa/search?utf8=%E2%9C%93&q=GL_ARB_sampler_objects

This is the actual driver so I think there is a good chance that it will work.

**Comment by tl8roy** [comment]
To use the driver on an older pi: https://github.com/anholt/mesa/issues/55

**Comment by tl8roy** [comment]
Looks like there is progress, Although I don't know what that error means.

And I can confirm that the Pi has ```GL_ARB_sampler_objects```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Texture(FormatNotSupported)', /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
stack backtrace:
   1: 0x552c6efb - std::sys::imp::backtrace::tracing::imp::write::h02b78b2e65532368
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x552ca417 - std::panicking::default_hook::{{closure}}::hffe708e5cc715405
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:349
   3: 0x552c9eaf - std::panicking::default_hook::hc370387b5f1e987c
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:365
   4: 0x552ca913 - std::panicking::rust_panic_with_hook::hddd209bbdef27fcf
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:553
   5: 0x552ca77f - std::panicking::begin_panic::h52b0f48bae4717fb
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:515
   6: 0x552ca703 - std::panicking::begin_panic_fmt::h09a380d7a08e85e0
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:499
   7: 0x552ca69f - rust_begin_unwind
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:475
   8: 0x552ed61b - core::panicking::panic_fmt::h61dd8cab740e10fc
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libcore/panicking.rs:69
   9: 0x54be4fff - core::result::unwrap_failed::h967c90a8acd75c66
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libcore/macros.rs:29
  10: 0x54bc1ca3 - <core::result::Result<T, E>>::unwrap::h571563dc31a6c0cc
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libcore/result.rs:737
  11: 0x54cd87e7 - glutin_glium::feature::main::h12008ddc27515efe
                at /home/tlostroh/blu/conrod-glium_glsl_120/examples/glutin_glium.rs:75
  12: 0x54cd84b7 - glutin_glium::main::h094bb12a6d452163
                at /home/tlostroh/blu/conrod-glium_glsl_120/examples/glutin_glium.rs:10
  13: 0x552cf88b - __rust_maybe_catch_panic
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libpanic_unwind/lib.rs:98
  14: 0x552cafc7 - std::rt::lang_start::hf13b8f7bdf23c3b4
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:434
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/panic.rs:351
                at /buildslave/rust-buildbot/slave/beta-dist-rustc-cross-host-linux/build/src/libstd/rt.rs:57
```

**Comment by mitchmindtree** [comment]
@tl8roy I'm going to have a go at getting my old raspberry pi going so that I can test this, but just want to check I'm using the same OS first - are you running Raspbian or something else?

**Comment by mitchmindtree** [comment]
In the meantime, it could be worth testing if [this glium example](https://github.com/tomaka/glium/blob/cd1bab4f6b7c3b48391289b3a10be115f660b252/examples/image.rs) works on your Pi, as it seems to support even older shaders. If it turns out that example works for you, maybe we can try modify the type of textures we use in the glium backend to match it.

**Comment by tl8roy** [comment]
@mitchmindtree Yes, we are using Raspbain.

**Comment by tl8roy** [comment]
Right, good news, that example works.

**Comment by mitchmindtree** [comment]
Nice! I'm backing up and flashing my Pi as I type this, hopefully will be able to get testing soon and have something working by the end of the day :+1:

**Comment by mitchmindtree** [comment]
@tl8roy I managed to get the OpenGL 2.1 driver installed on my old Pi after a decent amount of hacking at various configs. Running `glxgears` seemed to seemed to run efficiently with the proper lighting and `glxinfo` displayed the correct OpenGL 2.1 driver.

I then installed rust on the pi itself (I couldn't find any recent guides on cross compiling from macOS to ARM linux) and ran the initial build which took about 6 hours. It successfully built all crates until it got to the `glium` crate, at which point it just returned ```error: could not compile `glium` ``` with no further explanation (using --verbose didn't provide any more info). Did you run into anything like this when building on your Pi? I'm currently unsure where to go from here... Will keep thinking while addressing some other issues in the meantime.

**Comment by tl8roy** [comment]
@mitchmindtree ```rustc``` performance is poor on single core machines (And VMs).
I found I had to use nightly to get it to build on ARM.

I actually use a Ubuntu VM to cross compile (Following this: https://github.com/japaric/rust-cross).

And I have just realised that the Pi that you have has the ARMv6 instruction set which causes issues.

**Comment by mitchmindtree** [comment]
OK everything seems to be compiling and I'm getting the same `panic!` that you were, so good sign so far!

Doing some further digging, the problem seems to be the format of the texture used for caching text. Currently, the format used is `U8`, whereas this is only supported in versions greater than or equal to GL 3.0 and GL ES 3.0. It seems we should be able to use the `U8U8U8` format, as this has been supported since OpenGL 1.1. I'm having a go at getting this working now.

**Comment by tl8roy** [comment]
Good news, the screen now renders properly with reasonable performance full screen.
I'll do some more testing and close this job off once that is done.

**Comment by tl8roy** [comment]
So on the whole, it is working pretty well.

Some of the colours seem to be a bit off though.

**Comment by mitchmindtree** [comment]
Hmmm I've also noticed this too - they seem a little darker / more
contrasted? Not sure what it might be though... doesn't seem like anything
in the new shader should make a difference. Have you noticed this
difference with any other gl programs on your pi? Could be worth checking
the tomaka/glium image.rs example too.

**Comment by tl8roy** [comment]
Could it be something to do with sRGB and RGB?

I think there was something last year where they were too light.

The ```glxgears``` appear to be right. I might try a different image with the ```image``` example.

**Comment by tl8roy** [comment]
It looks like that the tomaka/glium image.rs example has the same issue.

**Comment by tl8roy** [comment]
Looking at the Glium issue list https://github.com/tomaka/glium/issues/805 looks to describe the problem.

Not sure how it affects Conrod or if it should be auto detected.

**Comment by tl8roy** [comment]
I don't know if they are related at all, but I am working an issue with the display. https://github.com/anholt/linux/issues/93

What might make it related is that a basic Conrod binary doesn't go out of range, but a basic one does.
I haven't tried the examples yet.

**Comment by anholt** [comment]
As far as texture formats, I'm guessing that "U8" means "R8 unsigned normalized".  You need the texture_rg extension for that, and have to use alpha, luminance, or intensity instead if you don't have texutre_rg.  If you only ever reference the 'x' channel of your samples from U8, then just falling back to intensity would do.

**Comment by anholt** [comment]
Also, gdb breakpoints on _mesa_error can be really useful for figuring out what you did to anger the GL implementation, if you haven't hooked up GL_ARB_debug_output for printing messages.

**Comment by tl8roy** [comment]
Based on where we got on the the other issue, I think it is possible that the problem is located somewhere on this side of the stack.
